project_id = "bpjinatcgdmxqetfxjji"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 10000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54329

[rest]
enabled = true
port = 54321

[realtime]
enabled = true
port = 54328

[functions.cleanup-expired-bookings]
verify_jwt = false

[functions.cleanup-incomplete-matches]
verify_jwt = false

[functions.booking-webhook]
verify_jwt = false

[functions.create-rodrigo-user]
verify_jwt = false

[functions.get-matches]
verify_jwt = false

[functions.get-users-with-auth]
verify_jwt = false

[functions.manage-user-role]
verify_jwt = false

[functions.manual-user-creation]
verify_jwt = false

[functions.process-registration-request]
verify_jwt = false

[functions.update-user-auth]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false