
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Export the supabase client from our main client file to ensure consistency
export { supabase } from '@/lib/supabase-client';
